---
- name: Update Arista fabric configuration
  hosts: dc1-spine2
  gather_facts: false

  # vars:
  #   repository: https://github.com/mzdyb/avd-aap
  #   branch: main
  #   artifacts_folder: artifacts
  #   changes_name: "Configuration changes by Ansible Automation Platform"
  #   changes_description: |
  #     Triggered by commit: {{ artifacts_repository }}/commit/{{ awx_project_revision }}
  #     Job: https://{{ awx_execution_node }}/execution/jobs/playbook/{{ awx_job_id }}

  tasks:
    - name: Retrieve repository
      ansible.scm.git_retrieve:
        origin:
          url: "{{ repository }}"
        branch:
          name: "{{ branch }}"
          duplicate_detection: false
      delegate_to: localhost
      run_once: true
      register: repository

    - name: Generate AVD Yaml Structured Configurations and Fabric Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_designs
      vars:
        root_dir: "{{ repository['path'] }}/{{ artifacts_folder }}"

    - name: Generate Device Configurations and Documentation
      ansible.builtin.import_role:
        name: arista.avd.eos_cli_config_gen
      register: eos_config
      vars:
        root_dir: "{{ repository['path'] }}/{{ artifacts_folder }}"

    - name: Deploy Configurations to Devices
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_eapi
      vars:
        root_dir: "{{ repository['path'] }}/{{ artifacts_folder }}"


    # - name: Publish artifacts
    #   when: eos_config.changed
    #   run_once: true
    #   delegate_to: localhost
    #   ansible.scm.git_publish:
    #     commit:
    #       message: |
    #         {{ changes_name }}

    #         {{ changes_description }}
    #         {% if cv_deploy_results.change_control.id is not none %}
    #         Change Control: https://{{ cv_server }}/cv/provisioning/change-control?ccId={{ cv_deploy_results.change_control.id }}
    #         {% else %}
    #         CloudVision designed configuration was already up to date. No Change Control created.
    #         {% endif %}
    #     token: "{{ github_pat }}"
    #     path: "{{ repository['path'] }}"
    #     include: ["{{ artifacts_folder }}"]
