---
- name: Validate devices operational states
  hosts: all
  connection: local
  gather_facts: false

  tasks:
    - name: Test network states
      import_role:
        name: arista.avd.anta_runner
      vars:
        root_dir: "{{ inventory_dir }}/{{ artifacts_folder }}"
