---
- name: Push artifacts to SCM
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Push artifacts to Github
      ansible.scm.git_publish:
        commit:
          message: "artifacts data updated"
        # token: "{{ github_token }}"
        token: "{{ github_pat }}" 
        path: ../
        # path: "{{ inventory_dir }}"
        include: artifacts
        # include: "{{ artifacts_folder }}"

    # - name: Push Build Design to SCM 
    #   ansible.scm.git_publish:
    #     path: "{{ _repo['path'] }}"
    #     commit:
    #       message: "Ansible commit at {{ now(utc=true,fmt='%Y-%m-%d %H:%M:%S') }}"
    #     remove: true
    #     token: "{{ git_token }}"
    #     tag:
    #       message: "{{ git_tag_name }}"
    #       annotation: "{{ git_tag_annotation | default(now(utc=true,fmt='%Y-%m-%d-%H-%M-%S')) }}"
    #   run_once: true
    #   check_mode: false