name: Build, deploy and validate operational states of Arista EOS devices using Ansible Automation Platform

on:
  push:
    branches:
      - main

jobs:

  trigger_workflow_template:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke "Arista AVD - build, deploy and validate operational states" workflow template webhook
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: ${{ secrets.WEBHOOK_URL_AVD_AAP }}
        webhook_secret: ${{ secrets.WEBHOOK_SECRET_AVD_AAP }}
        verify_ssl: false